# Generated by Django 3.0.4 on 2020-04-11 10:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(1, 'รอการอนุมัติ'), (2, 'อนุมัติ'), (3, 'ไม่อนุมัติ')], default=1)),
                ('status_remark', models.IntegerField(choices=[(1, 'รอการอนุมัติ'), (2, 'อนุมัติ'), (3, 'ไม่อนุมัติ')], default=1)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=255)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('year', models.IntegerField(choices=[(1, 'it'), (2, 'dsba'), (3, 'bit')])),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Room_type')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('teacher_result', models.BooleanField(default=False)),
                ('staff_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('staff_result', models.BooleanField(default=False)),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Booking')),
                ('staff_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Staff')),
                ('teacher_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_list',
            fields=[
                ('list_no', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Booking')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Adminn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
