# Generated by Django 3.0.5 on 2020-04-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_list',
            name='bookdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
