# Generated by Django 3.0.5 on 2020-04-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200423_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_student',
            name='staff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='staff_result',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='staff_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff'),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='teacher_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='teacher_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Teacher'),
        ),
    ]
