# Generated by Django 3.0.4 on 2020-04-16 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200416_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bookdate',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
