# Generated by Django 3.0.5 on 2020-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200424_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_student',
            name='staff_result',
            field=models.BooleanField(default=False),
        ),
    ]
