# Generated by Django 3.0.4 on 2020-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_booking_bookdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookdate',
            field=models.DateField(),
        ),
    ]
