# Generated by Django 3.0.5 on 2020-04-19 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200416_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.IntegerField(choices=[(1, 'it'), (2, 'dsba'), (3, 'bit')], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.IntegerField(choices=[(1, 'นักศึกษา'), (2, 'อาจารย์'), (3, 'บุลคลากร')], default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(),
        ),
    ]
