# Generated by Django 3.0.5 on 2020-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200424_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_student',
            name='staff_result',
            field=models.IntegerField(choices=[(1, 'รอการอนุมัติ'), (2, 'อนุมัติ'), (3, 'ไม่อนุมัติ')], default=1),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='teacher_result',
            field=models.IntegerField(choices=[(1, 'รอการอนุมัติ'), (2, 'อนุมัติ'), (3, 'ไม่อนุมัติ')], default=1),
        ),
    ]
