# Generated by Django 3.0.5 on 2020-04-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200419_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='role',
        ),
    ]
