# Generated by Django 3.0.5 on 2020-04-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200419_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
