# Generated by Django 3.0.5 on 2020-04-22 12:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_student',
            name='staff_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='staff_user_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Staff'),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='teacher_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='booking_student',
            name='teacher_user_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='user.Teacher'),
            preserve_default=False,
        ),
    ]
