# Generated by Django 3.0.5 on 2020-04-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200422_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'นักศึกษา'), (2, 'อาจารย์'), (3, 'บุคคลากร')])),
            ],
        ),
    ]
