# Generated by Django 3.0.5 on 2020-04-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200422_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.IntegerField(blank=True, choices=[(1, 'it'), (2, 'dsba'), (3, 'bit')]),
        ),
    ]
